### ISSUE TITLE
Invite Based Batch Membership

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#111]
### Why?

Currently, the only way to join a batch is through the Course Details Page, where the student can view upcoming batches and join a batch that suits them. But this isn't possible if the batch is private. Private batches don't appear on the Course Details page. Mentors can add students to this batch via Desk. But not all mentors will have desk access. So such a mentor won't be able to add students to the batch.

### Solution - Invite based Batch Membership

1. We already have a select field called Membership in LMS Batch doctype with options such as Open, Restricted, Invite Only, Closed. 
2. For Batches that are private, the membership can be Invite Only. For such batches, an invite link will be visible to the mentor on the ~~Course Details~~ Batch home Page. The mentor can then share this link with the students he wants to add to this batch.
3. When a student uses the link a form will be displayed to them. The form will only ask for their email address. Batch and course information will be prefilled and read-only. On submit, membership for that batch will be created for the student. They will be redirected to the Batch home page.

### Possible Scenarios

1. What if the student who uses the link is not a user of the community? Such users can be shown a message asking them to signup before they join this batch. They can then be redirected to the signup page. For mon_school we don't have a signup page as of now. They can be redirected to the home page where they can request an invitation. Decision for mon school depends on #110

**Comment by anandology** [comment]
> For Batches that are private, the membership can be Invite Only. For such batches, an invite link will be visible to the mentor on the Course Details Page. The mentor can then share this link with the students he wants to add to this batch.

The invite link could be there even for batches that are open. Mentor may want to promote the course by sharing the link to signup.

> When a student uses the link a form will be displayed to them. The form will only ask for their email address. Batch and course information will be prefilled and read-only. On submit, membership for that batch will be created for the student. They will be redirected to the Batch home page.

Nope. Think of what happens when someone invites you to a github repo. There is no form to fill anything. You click on the link and it will ask you for your confirmation to join the batch. Once you confirm you are part of the batch. 

The catch is that the link is accessible only to the logged-in yours. If you are not logged in, it will take you to the login page and you'll be redirected back to same page after login.

> ### Possible Scenarios
> 
>     1. What if the student who uses the link is not a user of the community? Such users can be shown a message asking them to signup before they join this batch. They can then be redirected to the signup page. For mon_school we don't have a signup page as of now. They can be redirected to the home page where they can request an invitation. Decision for mon school depends on #110

Since the invite-link page is only accessible to the logged in users, there is no possibility of this scenario.
