### ISSUE TITLE
Redesign Issues

### ISSUE THREAD

**Issue by pateljannat** [fossunited/community#146]
**This thread will keep a track of all redesign issues.**

- [x] Responsive issues on Course Home Page for some devices
- [x] Continue Course button on the course card should redirect to the Current Lesson and not Course Home
- [x] Start Learning should redirect to the Lesson page and not the old course home

**Comment by v-pai** [comment]
# Course outline and Course creator

The headings 
- Each of the headings have a margin-top. This becomes a problem if we want to re-position the headings at some point in the future. Instead of adding margin values to the header, we can add a `margin-top` to the entire section.
![image showing margin values](https://user-images.githubusercontent.com/81136551/124905684-e9fb0d00-e003-11eb-908b-592285574e02.png). I see there's good value in having one common margin across sections.

Following is my suggestion:
```diff
. course-outline-instructor-parent {
+ margin-top: 3rem;
}

.course-home-headings {
- margin: 48px 0 16px;
+ margin-bottom: 1rem;
}
```

Post this, the section would look like:
![common margin across sections](https://user-images.githubusercontent.com/81136551/124906496-bec4ed80-e004-11eb-8b82-33671c0450c3.png)


---

## Lesson info

Remove left padding
- I had added the left padding when we had numbers next to the lesson names. But since we decided to have numbers for the chapters, we should remove the left padding to ensure the text is aligned well.

My suggestion:
```diff
.lesson-info {
/* remove left padding */
- padding-left: 10px; 
- margin-bottom: 2px;
}
```

---

## Open Chapter

Chapter description and lessons. We can improve the hover state for lessons. This is my mistake, I didn't include it in figma but here's my suggestion for the hover state  

For chapter title
```diff
.chapter-title {
- margin: 0 5px 16px;
+ margin: 0 .25rem .5rem;
```

```diff
.chapter-content {
- margin: 4px 0 0 28px;
+    margin: 0;
+ margin-left: .875rem;
```

```diff
.chapter-description {
- margin-bottom: 10px;
+ margin-left: .75rem;
```

For lessons

Not sure `.dark-links` is a good class name. We could rename it to `lesson-links`. The following css will help with the designing the hover state.

```diff
.lesson-links {
+ display: block;
+ padding: 0 1rem;
+ margin-bottom: .25rem;
}
```

```diff
.lesson-links:hover {
+ cursor: pointer
+ text-decoration: none;
+ background: #F4F5F6;
+ border-radius: .25rem;
```

For chapter descriptions

```diff
.chapter-description {
- margin-bottom: 8px;
/*remove extra bottom margin*/
+    margin-bottom: 0;
/*align chapter description to lessons*/
+    padding-left: .5rem;
```

---

The card divider seems a bit too strong when actually implemented. I'm making the color a little lighter to balance it out. We should remove the margin bottom from the divider and control this spacing at the lesson level. This will increase the hit area for the closed lessons as well.

```diff
.card-divider {
+ border: 1px solid #F4F5F6;
- margin-bottom: 16px;
}
```

---

For the chapter title

```diff
.chapter-title {
+ display: flex;
+ align-items: center;
```

We should update the arrow svg as well. I will send the new arrow svg to you first thing tomorrow morning. There are some more spacing fixes to be made here but we should do that once we update the svgs

**Comment by v-pai** [comment]
# Mentor cards

Mentor cards need to be end-to-end and aligned to the creator card above.

```diff
.mentors-section {
+    justify-content: space-between;
```

```diff
.member-card-medium {
-    margin: 0 20px 32px 0;
```

This fixes the alignment issue but when we click on 'View All Mentors', the new card is rendered in the same row. To avoid this, we need to add an element that will act as a line break.

```diff
<div class="common-card-style member-card member-card-medium ">
    <a href="/jennie">
        <span class="avatar avatar-large" title="Jennie Kim"><img class="avatar-frame standard-image" style="object-fit: cover;" src="/files/jennie.jpeg" title="Jennie Kim"></span>
    </a>
    <div class="small-title member-card-title">
        Jennie Kim
    </div>
  <a class="stretched-link" href="/jennie"></a>
</div>

+ <div class="break"></div>

<div class="common-card-style member-card member-card-medium wrapped" style="">
    <a href="/jannat">
        <span class="avatar avatar-large" title="Jannat Patel"> <img class="avatar-frame standard-image" style="object-fit: cover;" src="/files/myprofile.jpg" title="Jannat Patel"></span>
    </a>
    <div class="small-title member-card-title">
        Jannat Patel
    </div>
    <a class="stretched-link" href="/jannat"></a>
</div>
```

```diff
+ .break {
+ flex-basis: 100%;
+ flex-grow: 1;
+ margin: .5rem 0;
+}
```

```diff
.view-all-mentors {
+ margin-top: 1rem;
}
```

**Comment by v-pai** [comment]
All courses page is off-center
<img width="1680" alt="CleanShot 2021-07-08 at 23 32 31@2x" src="https://user-images.githubusercontent.com/81136551/124969833-cd32f980-e044-11eb-8d28-98ace07831d4.png">

**Comment by v-pai** [comment]
### Cards Parent

```diff
.cards-parent {
    display: flex;
    flex-wrap: wrap;
+   justify-content: space-between;
}    
```

```diff
.course-card {
+ margin-right: 0;
- height: 380px;
}
```

---

### Course Card

```diff
.course-card {
+    border: 1px solid #EEF0F2;
+    box-shadow: 0 1px 4px 4px rgb(25 39 52 0.02);
}
```

```diff
.course-image {
-    width: 352px; 
+    width: 100%;
}
```

```diff
.course-tags {
    display: flex;
-    position: relative;
-   top: 12px;
-    left: 12px;
-    height: 20px;
+    position: absolute;
+   top: 1rem;
+    left: 1rem;
}
```

```diff
.course-card-pills {
+    margin-left: 0;
+    margin-right: .5rem;
}
```

**Comment by v-pai** [comment]
## Unable to start learning a course

<img width="1387" alt="CleanShot 2021-07-08 at 23 57 11@2x" src="https://user-images.githubusercontent.com/81136551/124972697-4da72980-e048-11eb-8a6f-e4a0806153a1.png">

Actions I performed
- From 'All Courses', clicked on a course
- Clicked on 'Start Learning'
- Got a message saying that I'm a student of the course
- Following this, the above-mentioned error shows up
- Went back to 'Home'
- Clicked on 'Continue Course', the error persists

**Comment by anandology** [comment]
## YouTubeVideo is not responsive

<img width="452" alt="Screenshot 2021-07-13 at 10 18 00 AM" src="https://user-images.githubusercontent.com/7569/125392456-d2d16c00-e3c3-11eb-990d-82690e5bb94a.png">

**Comment by anandology** [comment]
## Aspect ratio of Preview image

The aspect ratio of the uploaded image are not maintained and that is causing a skew in the image.

<img width="1152" alt="Screenshot 2021-07-13 at 10 28 02 AM" src="https://user-images.githubusercontent.com/7569/125393205-23959480-e3c5-11eb-995a-ccdc0ca82707.png">

**Comment by anandology** [comment]
## font size of h2 and h3 inside the lesson

<img width="785" alt="Screenshot 2021-07-15 at 5 23 41 AM" src="https://user-images.githubusercontent.com/7569/125707293-42053e46-7aee-40b6-b31e-973eba9e3101.png">

The heading _Fill Color_ in the lesson is `h2` and it is appearing bigger than the title of the lesson on the top. 

I think we should redefine the font-size of h2, h3 and h4 relative to the font-size of lesson heading.

**Comment by anandology** [comment]
# Mark as Compelete not adding the tick

When I click on mark as complete, the title of the lesson gets a label _COMPLETED_, but the sidebar doesn't show the tick until the page is refreshed.

<img width="1164" alt="Screenshot 2021-07-15 at 6 02 50 AM" src="https://user-images.githubusercontent.com/7569/125710371-891837d3-ff07-4684-a8c4-d3d37bb9ee30.png">
